import React, { Component } from "react";
import Typical from 'react-typical';

class TypingAnimation extends Component {
  render() {
    return (
      <Typical
        steps={[
          "",
          1000,
          "H",
          150,
          "Hi",
          150,
          "Hi,",
          150,
          "Hi, ",
          150,
          "Hi, I",
          150,
          "Hi, I'",
          150,
          "Hi, I'm",
          150,
          "Hi, I'm ",
          150,
          "Hi, I'm B",
          150,
          "Hi, I'm Bo",
          150,
          "Hi, I'm Boz",
          150,
          "Hi, I'm Boze",
          150,
          "Hi, I'm Bozen",
          150,
          "Hi, I'm Bozena",
          150,
          "Hi, I'm Bozena.",
          150,
          "Hi, I'm Bozena. ",
          150,
          "",
          1000,
          "I",
          150,
          "I ",
          150,
          "I d",
          150,
          "I de",
          150,
          "I des",
          150,
          "I desi",
          150,
          "I desig",
          150,
          "I design",
          150,
          "I design ",
          150,
          "I design &",
          150,
          "I design & ",
          150,
          "I design & b",
          150,
          "I design & bu",
          150,
          "I design & bui",
          150,
          "I design & buil",
          150,
          "I design & build",
          150,
          "I design & build ",
          150,
          "I design & build w",
          150,
          "I design & build we",
          150,
          "I design & build web",
          150,
          "I design & build webs",
          150,
          "I design & build websi",
          150,
          "I design & build websit",
          150,
          "I design & build website",
          150,
          "I design & build websites",
          150,
          "I design & build websites.",
          300
        ]}
        loop={Infinity}
        wrapper="p"
      />
    );
  }
}

export default TypingAnimation;
